### PR TITLE
Adding Vanilla version 1.4.2.2

### PR DESCRIPTION
**Pull request by cyb3rsyph0n**
Adding Vanilla version 1.4.2.2 for auto build

### CODE REVIEW

**Comment by voidpumpkin** [comment]
Cant wait for this to merge!

**Comment by voidpumpkin** [comment]
@cyb3rsyph0n Heads up, there are more fields to update: https://github.com/beardedio/terraria/commit/8d7b6b819d837c669a68ebb84ac116250cbe2572

**Comment by cyb3rsyph0n** [comment]
I thought the auto scripts ran as part of the nightly build for the other files. I just updated the one locally and ran the bin files to get a build running for my self and friends.

If it's preferred to run the update scripts and submit all the changes in a PR I can do that. I just thought the scripts updated everything every night anyway.

**Comment by hskrtich** [comment]
These changes have been integrated and the docker images have been updated. Thank you for the PR!

**Pull request closed without merging**
